/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;


import Model.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import Business.EcoSystem;
import Model.Menu;
import Model.Order;
import Model.Customer;

/**
 *
 * @author raunak
 */
public class CustomerAreaJPanel1 extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    
    private UserAccount userAccount;
    private EcoSystem system;
    private Menu menu;
    private Order order;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public CustomerAreaJPanel1(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        
        this.userAccount = account;
        this.system = system;
        populateCombo();
        txtCustomer.setText(userAccount.getUsername());
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequest = new javax.swing.JButton();
        lbMenu = new javax.swing.JLabel();
        comMenu = new javax.swing.JComboBox<>();
        lbPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lbRestaurant = new javax.swing.JLabel();
        comRestaurant = new javax.swing.JComboBox<>();
        btnPast = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();

        btnRequest.setText("Confirm");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        lbMenu.setText("Choose Menu:");

        comMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comMenuActionPerformed(evt);
            }
        });

        lbPrice.setText("Total Price:");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        lbRestaurant.setText("Choose Restaurant:");

        comRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comRestaurantActionPerformed(evt);
            }
        });

        btnPast.setText("Past Orders");
        btnPast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastActionPerformed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbTitle.setText("Welcome:");

        txtCustomer.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(168, Short.MAX_VALUE)
                        .addComponent(lbTitle)
                        .addGap(18, 18, 18)
                        .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRequest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPast)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRestaurant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(61, 61, 61)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comRestaurant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrice))
                                .addGap(20, 20, 20)))))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRestaurant)
                    .addComponent(comRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMenu)
                    .addComponent(comMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrice))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(btnPast))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        
        String seletedRestaurant = String.valueOf(comRestaurant.getSelectedItem());
        String selectedMenu = String.valueOf(comMenu.getSelectedItem());
        String price = txtPrice.getText();
        Order order = new Order(userAccount.getUsername(),seletedRestaurant,selectedMenu,"","Request","");
        system.getRestaurantDirectory().getRestaurantAccountList().get(0).getOrders().add(order);
        for(Customer c : system.getCustomerDirectory().getCustomerList()){
            if(c.getUsername().equals(userAccount.getUsername())){
                c.getOrders().add(order);
            }
        }
        CustomerOrderJPanel ca = new CustomerOrderJPanel(userProcessContainer,userAccount,system,order);
        userProcessContainer.add("CustomerAreaJPanel",ca);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnPastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastActionPerformed
        // TODO add your handling code here:
        CustomerPastOrdersJPanel ca = new CustomerPastOrdersJPanel(userProcessContainer,userAccount,system);
        userProcessContainer.add("CustomerPastOrdersJPanel",ca);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_btnPastActionPerformed

    private void comRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comRestaurantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comRestaurantActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtPriceActionPerformed

    private void comMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comMenuActionPerformed
        // TODO add your handling code here:
         String selectedCombo = String.valueOf(comMenu.getSelectedItem());
         for(Menu m : system.getRestaurantDirectory().getRestaurantAccountList().get(0).getMenuList()){
             if(m.getType().equals(selectedCombo)){
                 txtPrice.setText(m.getPrice());
             }
         }
         
    }//GEN-LAST:event_comMenuActionPerformed

    private void txtCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerActionPerformed
     private void populateCombo() {
        comRestaurant.removeAllItems();
        comRestaurant.addItem(system.getRestaurantDirectory().getRestaurantAccountList().get(0).getName());
        populateCombo1();
        
            
        
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPast;
    private javax.swing.JButton btnRequest;
    private javax.swing.JComboBox<String> comMenu;
    private javax.swing.JComboBox<String> comRestaurant;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbRestaurant;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private void populateCombo1() {
        comMenu.removeAllItems();
        for(Menu m : system.getRestaurantDirectory().getRestaurantAccountList().get(0).getMenuList()){
            comMenu.addItem(m.getType()); 
        }
        
    }
}
