/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Product;
import model.ProductCatalog;
import UI.TimeUtil;
/**
 *
 * @author chen.wei
 */
public class createJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    ProductCatalog catalog;
    JPanel workArea;
    private TimeUtil tu = new TimeUtil();
    private static final String NUMBER = "^(19|20)\\d{2}$"; //year 1900-2199
    private static final String NUMBER1 = "^[0-9]+$"; //数字
    public createJPanel(JPanel workArea,ProductCatalog catalog) {
        initComponents();
        this.workArea = workArea;
        this.catalog = catalog;
        cmbIsAvailable.removeAllItems();
        cmbIsExpired.removeAllItems();
        cmbIsAvailable.addItem("Yes");
        cmbIsAvailable.addItem("No");
        cmbIsExpired.addItem("Yes");
        cmbIsExpired.addItem("No");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lbTitle = new javax.swing.JLabel();
        lbModelNumber = new javax.swing.JLabel();
        lbSeatNumbers = new javax.swing.JLabel();
        lbBrands = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        txtSeatsNumbers = new javax.swing.JTextField();
        txtBrands = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lbSerialNumber = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lbProduceYear = new javax.swing.JLabel();
        txtProduceYear = new javax.swing.JTextField();
        lbCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lbManufacturers = new javax.swing.JLabel();
        txtManufacturers = new javax.swing.JTextField();
        lbIsAvailable = new javax.swing.JLabel();
        lbIsExpired = new javax.swing.JLabel();
        cmbIsAvailable = new javax.swing.JComboBox<>();
        cmbIsExpired = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setSize(new java.awt.Dimension(600, 600));

        lbTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Create");

        lbModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbModelNumber.setText("Model Number");

        lbSeatNumbers.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSeatNumbers.setText("Seat Numbers");

        lbBrands.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBrands.setText("Brands");

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        txtSeatsNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsNumbersActionPerformed(evt);
            }
        });

        txtBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandsActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSerialNumber.setText("Serial Number");

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        lbProduceYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbProduceYear.setText("Produce Year");

        txtProduceYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduceYearActionPerformed(evt);
            }
        });

        lbCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCity.setText("City");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lbManufacturers.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbManufacturers.setText("Manufacturers");

        txtManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturersActionPerformed(evt);
            }
        });

        lbIsAvailable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbIsAvailable.setText("Is Available");

        lbIsExpired.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbIsExpired.setText("Is Expired");

        cmbIsAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIsAvailableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSeatNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSerialNumber)
                            .addComponent(lbCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbProduceYear, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(lbManufacturers)
                            .addComponent(lbIsAvailable)
                            .addComponent(lbIsExpired))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSeatsNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtBrands, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtProduceYear, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtManufacturers)
                            .addComponent(cmbIsAvailable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbIsExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnSave)))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbBrands, lbCity, lbIsAvailable, lbIsExpired, lbManufacturers, lbModelNumber, lbProduceYear, lbSeatNumbers, lbSerialNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBrands, txtCity, txtModelNumber, txtProduceYear, txtSeatsNumbers, txtSerialNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBrands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbModelNumber)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeatNumbers)
                    .addComponent(txtSeatsNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduceYear)
                    .addComponent(txtProduceYear, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbManufacturers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIsAvailable)
                    .addComponent(cmbIsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIsExpired)
                    .addComponent(cmbIsExpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBrands, txtCity, txtModelNumber, txtProduceYear, txtSeatsNumbers, txtSerialNumber});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbBrands, lbCity, lbIsAvailable, lbIsExpired, lbManufacturers, lbModelNumber, lbProduceYear, lbSeatNumbers, lbSerialNumber});

    }// </editor-fold>//GEN-END:initComponents

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void txtSeatsNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsNumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsNumbersActionPerformed

    private void txtBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
     
        int seatNumbers = Integer.parseInt(txtSeatsNumbers.getText());
        
        String brands = txtBrands.getText();
        
        String produceYear = txtProduceYear.getText();
        String serialNumber = txtSerialNumber.getText();
        String modelNumber = txtModelNumber.getText();
        String city = txtCity.getText();
        String manufacturers = txtManufacturers.getText();
        Product product = catalog.addNewProduct();
       
        if(Pattern.matches(NUMBER1,txtSeatsNumbers.getText())){
            product.setSeatNumbers(seatNumbers);   
        }else{
            JOptionPane.showMessageDialog(this, "Incorecct seatNumber format !");
        }
       
        product.setBrands(brands);
       if(Pattern.matches(NUMBER,produceYear)){
          product.setProduceYear(produceYear);
        }
        else{
            JOptionPane.showMessageDialog(this, "Incorecct produceYear format !");
        }
        //product.setProduceYear(produceYear);
        if(product.isNull(serialNumber)){
           JOptionPane.showMessageDialog(this, "serialNumber can't be null !");  
        }else{
           product.setSerialNumber(serialNumber);
        }
        //product.setSerialNumber(serialNumber);
        product.setModelNumber(modelNumber);
        product.setCity(city);
        product.setManufacturers(manufacturers);
        boolean isAvailable;
        boolean isExpired;
        if(cmbIsAvailable.getSelectedItem() == "Yes"){
            isAvailable = true;
        }else{
           isAvailable = false;
        }
        if(cmbIsExpired.getSelectedItem() == "Yes") {
            isExpired = true;
        }
        else{
            isExpired = false;
        }
        product.setIsAvailable(isAvailable);
        product.setIsExpired(isExpired);
        
        JOptionPane.showMessageDialog(this, "new product added");
        
        txtSeatsNumbers.setText("");
        txtBrands.setText("");
        txtProduceYear.setText("");
        txtSerialNumber.setText("");
        txtModelNumber.setText("");
        txtCity.setText("");
        txtManufacturers.setText("");
        tu.getTime();
   
             
        
        
    }//GEN-LAST:event_btnSaveActionPerformed
   
    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void txtProduceYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduceYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduceYearActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturersActionPerformed

    private void cmbIsAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIsAvailableActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_cmbIsAvailableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbIsAvailable;
    private javax.swing.JComboBox<String> cmbIsExpired;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lbBrands;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbIsAvailable;
    private javax.swing.JLabel lbIsExpired;
    private javax.swing.JLabel lbManufacturers;
    private javax.swing.JLabel lbModelNumber;
    private javax.swing.JLabel lbProduceYear;
    private javax.swing.JLabel lbSeatNumbers;
    private javax.swing.JLabel lbSerialNumber;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField txtBrands;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacturers;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtProduceYear;
    private javax.swing.JTextField txtSeatsNumbers;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
